name: Create Binaries

on:
  push:
    branches:
       - main
       - 'pre-releases/**'
  pull_request:
    branches:
       - main
       - 'pre-releases/**'
       - copernicusmarine-toolbox-v2

jobs:
  container-test-job:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:18.04
    timeout-minutes: 20

    steps:
    - name: Install dependencies into minimal dockerfile
      run: |
        # ubuntu dockerfile is very minimal (only 122 packages are installed)
        # need to install updated git (from official git ppa)
        apt update
        apt install -y software-properties-common
        apt-get install python3-launchpadlib -y
        add-apt-repository ppa:git-core/ppa -y
        # install dependencies expected by other steps
        apt update
        apt install -y git \
        curl \
        ca-certificates \
        wget \
        bzip2 \
        zip \
        unzip \
        xz-utils \
        maven \
        ant sudo locales
        # set Locale to en_US.UTF-8 (avoids hang during compilation)
        locale-gen en_US.UTF-8
        echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
        echo "LANGUAGE=en_US.UTF-8" >> $GITHUB_ENV
        echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.6-0'
        micromamba-binary-path: ${{ runner.temp }}/bin/micromamba
        environment-file: conda_environment_binary-old-linux.yaml
        environment-name: copernicusmarine-binary-old-linux
        condarc-file: .condarc
        cache-environment: true
        post-cleanup: 'all'

    - name: Build with PyInstaller
      shell: micromamba-shell {0}
      run: |
        make run-using-pyinstaller-ubuntu-20.04
        echo ubuntu-20.04

    - name: Set VERSION environment variable
      id: set-version
      shell: micromamba-shell {0}
      run: echo "VERSION=$(poetry version --short)" >> $GITHUB_OUTPUT

    - name: Upload binaries to ubnutu-old
      shell: micromamba-shell {0}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
          gh release upload v${{steps.set-version.outputs.VERSION}} dist/copernicusmarine_linux-20.04.cli#copernicusmarine-binary-linux-20.04-for-v${{steps.set-version.outputs.VERSION}}
