name: Run tests

on:
  pull_request_target:
    branches:
      - "main"
      - "release/**"
      - "pre-releases/**"


jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
       os: [macos-latest, ubuntu-latest, macos-13, self-hosted]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          micromamba-binary-path: ${{ runner.temp }}/bin/micromamba
          environment-file: conda_environment_test.yaml
          environment-name: copernicusmarine_test
          condarc-file: .condarc
          cache-environment: true
          post-cleanup: 'all'

      - name: Run tests
        env:
          COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
          COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
        run: make run-tests
        shell: micromamba-shell {0}
